import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import weaponNamesToImageUrls from "@/data/weapon_names_to_image_urls.json";
import WeaponImage from "@/components/weapons/WeaponImage";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  // Function to get weapon image URL
  const getWeaponImageUrl = (weaponName: string): string => {
    return (
      weaponNamesToImageUrls[
        weaponName as keyof typeof weaponNamesToImageUrls
      ] || ""
    );
  };

  // Example: Get some weapon names
  const weaponNames = Object.keys(weaponNamesToImageUrls);
  const firstFiveWeapons = weaponNames.slice(0, 5);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            src="/assets/images/stats/life.png"
            alt="Life Icon"
            width={32}
            height={32}
            priority
          />
          <Image
            src="/assets/images/stats/agility.png"
            alt="Agility Icon"
            width={32}
            height={32}
            priority
          />

          <WeaponImage weaponName="gazor" />

          {/* Display some weapons from the JSON data */}
          <div style={{ marginTop: "20px" }}>
            <h3>Sample Weapons:</h3>
            {firstFiveWeapons.map((weaponName) => (
              <div
                key={weaponName}
                style={{
                  margin: "10px 0",
                  display: "flex",
                  alignItems: "center",
                  gap: "10px",
                }}
              >
                <Image
                  src={getWeaponImageUrl(weaponName)}
                  alt={weaponName}
                  width={32}
                  height={32}
                />
                <span>{weaponName}</span>
              </div>
            ))}
          </div>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={100}
            height={20}
            priority
          />
          <div className={styles.intro}>
            <h1>To get started, edit the index.tsx file.</h1>
            <p>
              Looking for a starting point or more instructions? Head over to{" "}
              <a
                href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                Templates
              </a>{" "}
              or the{" "}
              <a
                href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
                target="_blank"
                rel="noopener noreferrer"
              >
                Learning
              </a>{" "}
              center.
            </p>
          </div>
          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                className={styles.logo}
                src="/vercel.svg"
                alt="Vercel logomark"
                width={16}
                height={16}
              />
              Deploy Now
            </a>
            <a
              className={styles.secondary}
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Documentation
            </a>
          </div>
        </main>
      </div>
    </>
  );
}
