import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import weaponNamesToImageUrls from "@/data/weapon_names_to_image_urls.json";
import weaponsData from "@/data/weapons.json";
import weaponIds from "@/data/weapon_ids.json";
import WeaponImage from "@/components/weapons/WeaponImage";
import { getWeaponImageUrlByName } from "@/components/weapons/WeaponUtils";
import { Weapon } from "@/types/weapon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  // Convert the weapons object to a typed array
  const weapons: Weapon[] = Object.values(
    weaponsData as Record<string, Weapon>
  );

  // Example usage: Get first 5 weapons
  const firstFiveWeapons = weapons.slice(0, 5);

  // Example: Find a specific weapon by name
  const pistol = weapons.find((weapon) => weapon.name === "pistol");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <WeaponImage weaponName="gazor" />

          {/* Display weapons array info */}
          <div
            style={{
              marginTop: "20px",
              padding: "20px",
              border: "1px solid #ccc",
            }}
          >
            <h3>Weapons Data:</h3>
            <p>Total weapons: {weapons.length}</p>
            {pistol && (
              <div>
                <h4>Found Pistol:</h4>
                <p>ID: {pistol.id}</p>
                <p>Name: {pistol.name}</p>
                <p>Level: {pistol.level}</p>
                <p>Cost: {pistol.cost}</p>
                <p>Max Range: {pistol.max_range}</p>
                <p>Effects: {pistol.effects.length}</p>
                <p>Passive Effects: {pistol.passive_effects.length}</p>
              </div>
            )}

            <h4>First 5 Weapons:</h4>
            <ul>
              {firstFiveWeapons.map((weapon) => (
                <li key={weapon.id}>
                  {weapon.name} (ID: {weapon.id}, Level: {weapon.level})
                </li>
              ))}
            </ul>
          </div>
        </main>
      </div>
    </>
  );
}
